project:
  type: website
  output-dir: docs

website:
  title: "Open Case Studies: The Biology of Ancestry"

format:
  html:
    grid:
      sidebar-width: 260px
    theme: cosmo
    css: style.css
    toc: true
    toc-location: left

glossary:
  path: glossary.yml
  popup: click
  show: true

bibliography: resources/references.bib
