---
title: "Ripples Ancestry Plot"
author: "Kate Isaac"
date: "2024-12-20"
output: html_document
---

```{r}
library(readr)
library(ggplot2)
library(tidyverse)
library(patchwork)
library(here)

ancestry_props <- 
  read_table(here("data/raw/AGR.without_related_chr10_maf001_LDp50_final_removesmallpops_shrinkBaganda.combined_fam.Q"), col_names = c("pop", "id", paste0("k", 1:7)))
ancestry_props_prelim <- ancestry_props

ancestry_props <- ancestry_props %>%
         mutate(pop = factor(case_when(pop == "ACB" ~ "African Caribbean",
                         pop == "ASW" ~ "African American",
                         pop == "CHB" ~ "Han Chinese",
                         pop == "Egyptians" ~ "Egyptian",
                         pop == "ESN" ~ "Esan",
                         pop == "GBR" ~ "British",
                         pop == "GIH" ~ "Gujarati",
                         pop == "GWD" ~ "Mandinka",
                         pop == "LWK" ~ "Luhya",
                         pop == "MSL" ~ "Mende",
                         pop == "MXL" ~ "Mexican",
                         pop == "Nama/Khoe-San" ~ "Nama",
                         pop == "RwandeseUgandan" ~ "Rwandese",
                         pop == "uganda_gwas_unknown" ~ NA_character_,
                         pop == "Batooro" ~ NA_character_,
                         pop == "Nyanjiro(Tanzania)" ~ NA_character_,
                         pop == "TSI" ~ "Italian",
                         pop == "YRI" ~ "Yoruba",
                         TRUE ~ pop),
                      levels = c("Nama", "Zulu", "Mende", "Esan", "Yoruba", "Mandinka", "African Caribbean", "African American", "Banyarwanda", "Banyankole", "Bakiga", "Barundi", "Rwandese", "Baganda", "Luhya", "Gumuz", "Somali", "Wolayta", "Oromo", "Amhara", "Egyptian", "Gujarati", "Mexican", "British", "Italian", "Han Chinese"))
            ) %>%
  drop_na()

ancestry_props_temp <- ancestry_props
write.table(ancestry_props, file = here("data/wrangled/ADMIXTURE_ancestry_props.Q"), row.names = FALSE, quote = FALSE)
```
Need to add superpopulation labels and sort by those.


```{r fig.width = 5, fig.height = 10}
plot1 <- ancestry_props %>% 
  pivot_longer(starts_with("k"), values_to = "prop", names_to = "which_k") %>%
  ggplot(aes(y=id,
             x=prop,
             fill = factor(which_k),
             group = pop)) +
  geom_bar(stat = "identity", position = "stack", width = 1) +
  facet_wrap(~pop, ncol=1, strip.position = "left", scale = "free_y") +
  theme(axis.text.y = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        legend.position = "none") +
  ylab("") +
  scale_fill_manual(breaks = c("k6", "k7", "k1", "k4", "k5", "k3", "k2"), 
                    values = c("#2B284B", "#FFE6AD", "#30A9E1", "#056EB5", "#2BA06A", "#EC5D25", "#A41252"))

```

```{r}
ggsave(here("img/mainplot.png"), plot=plot1)
```

#A41252 -- Maroon/Zulu color - k2

#FFE6AD -- Mustard color - k7

#056EB5 -- Blue/green color - k4

#EC5D25 -- Purple color - k3

#30A9E1 -- Green - k1

#2BA06A -- Dodger blue - k5

#2B284B -- Salmon/pink - k6


```{r, fig.width = 2, fig.height=10}
plot2 <- left_join(ancestry_props_temp %>% 
            select(!starts_with("k")) %>%  
            rownames_to_column(), 
          ancestry_props_temp %>% 
            select(starts_with("k")) %>% 
            mutate(which_k = names(.)[max.col(.)]) %>% 
            rownames_to_column() %>% 
            select(rowname, which_k), 
          by="rowname") %>% 
  group_by(pop, which_k) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  group_by(pop) %>% 
  top_n(1, count) %>% 
  ggplot(aes(x = -1, 
             y = fct_rev(pop), 
             fill = which_k)) + 
  geom_col(width=1) + 
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none") + 
  xlab("") + 
  ylab("") + 
  xlim(c(-1,0)) + 
  scale_fill_manual(breaks = c("k6", "k7", "k1", "k4", "k5", "k3", "k2"), 
                    values = c("#2B284B", "#FFE6AD", "#30A9E1", "#056EB5", "#2BA06A", "#EC5D25", "#A41252"))
```

```{r fig.width = 5.5, fig.height = 12}
plot1 + plot2 + 
  plot_layout(widths = c(5,0.5), heights=c(12))
```

```{r}
ggsave(here("img/ancestry_props.png"))
```
